# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Promotion PR

on:
  push:
    branches:
      - dev
      - stage

permissions:
  contents: read
  pull-requests: write

jobs:
  promotion-pr:
    name: Promotion PR
    uses: kirchDev/workflows/.github/workflows/_promotion-pr.yml@b7bc3408448d1c0c1266e8c5fe2788c9cf120790 # v0.5.0
