# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Promotion PR

on:
  push:
    branches:
      - dev
      - stage

permissions:
  contents: read
  pull-requests: write

jobs:
  promotion-pr:
    name: Promotion PR
    uses: kirchDev/workflows/.github/workflows/_promotion-pr.yml@7fd4eaf529500fcd07c527ae70c839ab9ac7d76f # v0.7.0
